#
# Module manifest for module 'PS.Capa.CapaOne'
#
# Generated by: Nicolai Estrup Jacobsen
#
# Generated on: 27-06-2025
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'PS.Capa.CapaOne.psm1'

    # Version number of this module.
    ModuleVersion     = '0.1.1'

    # Supported PSEditions
    # CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    GUID              = '9251dfd1-ed57-45f4-9850-c50dbf4c0289'

    # Author of this module
    Author            = 'Nicolai Jacobsen'

    # Company or vendor of this module
    CompanyName       = ''

    # Copyright statement for this module
    Copyright         = '(c) Nicolai Jacobsen. All rights reserved.'

    # Description of the functionality provided by this module
    Description       = 'Interact with the CapaOne API to manage devices, users, groups, and MDM configurations. This module provides cmdlets for retrieving device information, managing MDM configurations, and handling enrollment processes.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @('Microsoft.PowerShell.Utility','Microsoft.PowerShell.Security')

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @('LoadClasses.ps1')

    # Type files (.ps1xml) to be loaded when importing this module
    TypesToProcess    = @('Capa.CapaOne.Types.ps1xml')

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @('Add-CapaOneDeviceToGroup', 'Connect-CapaOne', 'Get-CapaOneApplication', 'Get-CapaOneConnectionResponse', 
    'Get-CapaOneContracts', 'Get-CapaOneCustomApp', 'Get-CapaOneCustomAppIcon', 'Get-CapaOneDevice', 'Get-CapaOneDeviceAODLogs', 
    'Get-CapaOneDeviceGroup', 'Get-CapaOneDeviceInventory', 'Get-CapaOneDeviceUpdate', 'Get-CapaOneEnrollment', 'Get-CapaOneGroup', 
    'Get-CapaOneIntegration', 'Get-CapaOneMDM', 'Get-CapaOneMDMAndroidEndpoint', 'Get-CapaOneMDMAppleApplication', 
    'Get-CapaOneMDMAppleCertificate', 'Get-CapaOneMDMAppleConfiguration', 'Get-CapaOneMDMAppleEndpoint', 
    'Get-CapaOneMDMAppleEnrollmentConfiguration', 'Get-CapaOneMDMAppleVPP', 'Get-CapaOneReport', 'Get-CapaOneSessionVariable', 
    'Get-CapaOneTag', 'Get-CapaOneUser', 'Get-CapaOneUserProfile', 'New-CapaOneGroup', 'Remove-CapaOneDeviceFromGroup', 
    'Remove-CapaOneGroup', 'Sync-CapaOneIntegration', 'Update-CapaOneGroup')

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport   = '*'

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport   = '*'

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags         = @('API','CapaSystems','CapaOne','MDM','PowerShell','Endpoint','Enrollment')

            # A URL to the license for this module.
            # LicenseUri = ''

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/AniTexs/PS.Capa.CapaOne'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            ReleaseNotes = 'Updated Get-Help to include examples and descriptions for all functions. Added missing parameters to Get-CapaOneMDM and Get-CapaOneEnrollment.'

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    HelpInfoURI       = 'https://github.com/AniTexs/PS.Capa.CapaOne/tree/main/Documentation'

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    #DefaultCommandPrefix = 'Capa.CapaOne'

}


