name: Publish to PowerShell Gallery
run-name: ${{ github.actor }} is releasing PS.Capa.CapaOne

on:
  push:
    branches:
      - main
    paths:
      - "PS.Capa.CapaOne/**"
  workflow_dispatch:


jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
      issues: write
    runs-on: windows-latest
    steps:
      #- name: Publish to PowerShell Gallery
      #  env:
      #    APIKEY : ${{ secrets.PSGALLERY_APIKEY }}
      #  shell: pwsh
      #  run: |
      #    .\Publish-Module.ps1

      - name: Publish PowerShell Module
        uses: natescherer/publish-powershell-action@v1
        with:
          token: ${{ secrets.PSGALLERY_APIKEY }}
          target: gallery
          path: PS.Capa.CapaOne