name: Publish to PowerShell Gallery
run-name: ${{ github.actor }} is releasing PS.Capa.CapaOne

on:
  push:
    branches: [ main ]
    paths:
      - "PS.Capa.CapaOne/**"
      #- ".github/workflows/**"
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Publish to PowerShell Gallery
        env:
          APIKEY: ${{ secrets.PSGALLERY_APIKEY }}
        shell: pwsh
        run: |
          ./Publish-Module.ps1
